//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class house_detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public house_detail()
        {
            this.meter_details = new HashSet<meter_detail>();
        }
    
        public string HiD { get; set; }
        public string SiD { get; set; }
        public string House_No { get; set; }
        public string Owner_Name { get; set; }
        public string Owner_Mobile { get; set; }
        public string Owner_Email { get; set; }
        public string Tenant_Name { get; set; }
        public string Tenant_Email { get; set; }
        public string Tenant_Mobile { get; set; }
        public string Maintainance_Notes { get; set; }
    
        public virtual site_detail site_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meter_detail> meter_details { get; set; }
    }
}
