//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterType
    {
        public short ID { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Type { get; set; }
        public string Protocol { get; set; }
        public string RegisterType { get; set; }
        public Nullable<int> RegisterAddress { get; set; }
    }
}
