//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class meter_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public meter_master()
        {
            this.meter_details = new HashSet<meter_detail>();
        }
    
        public string MMiD { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Type { get; set; }
        public string Protocol { get; set; }
        public string Register_Type { get; set; }
        public string Address { get; set; }
        public string Import_Export { get; set; }
        public Nullable<short> RiD { get; set; }
        public Nullable<short> PiD { get; set; }
        public Nullable<short> TiD { get; set; }
        public Nullable<short> IiD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meter_detail> meter_details { get; set; }
        public virtual ProtocolType ProtocolType { get; set; }
        public virtual Register Register { get; set; }
        public virtual Table_1 Table_1 { get; set; }
        public virtual Table_2 Table_2 { get; set; }
    }
}
