//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organo
    {
        public string SiD { get; set; }
        public string House_No { get; set; }
        public string Owner_Name { get; set; }
        public string MiD { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Utility_Type { get; set; }
        public string IP_Address { get; set; }
    }
}
