//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public site_detail()
        {
            this.house_details = new HashSet<house_detail>();
            this.meter_details = new HashSet<meter_detail>();
        }
    
        public string SiD { get; set; }
        public string Site_Name { get; set; }
        public string Builder { get; set; }
        public string Logo { get; set; }
        public string Street_Road { get; set; }
        public string Area { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Pin_Code { get; set; }
        public string Lat { get; set; }
        public string Lon { get; set; }
        public string Contact_Person_Name { get; set; }
        public string Contact_Person_Mobile { get; set; }
        public string Contact_Person_Email { get; set; }
        public string Admin_Email { get; set; }
        public string Admin_Mobile { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<house_detail> house_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meter_detail> meter_details { get; set; }
    }
}
